### ISSUE TITLE
dropbox integration seems to be broken

### ISSUE THREAD

**Issue by cam156** [projecthydra/browse-everything#123]
In both Sufia 7 ScholarSphere and Sufia 6 ScholarShere we are getting an error when connecting to drop box.  I'm guessing this has something to do with the new dropbox api that came out in April.

When I click on Dropbox authorize 
And I login on drop box 
And click allow
Then I get the error

The Error message
```
2016-05-27 09:21:00 -0400 (87507) Started GET "/browse/connect?state=dropbox&code=MdnPzInOPPgAAAAAAAAAux8eOGOKVNw7NIUHyKqLMrI" for ::1 at 2016-05-27 09:21:00 -0400
2016-05-27 09:21:00 -0400 (87507) Processing by BrowseEverythingController#auth as HTML
2016-05-27 09:21:00 -0400 (87507)   Parameters: {"state"=>"dropbox", "code"=>"MdnPzInOPPgAAAAAAAAAux8eOGOKVNw7NIUHyKqLMrI"}
2016-05-27 09:21:00 -0400 (87507) Completed 500 Internal Server Error in 8ms (ActiveRecord: 0.0ms)
2016-05-27 09:21:00 -0400 (87507) 
DropboxOAuth2Flow::CsrfError - Expected "TfW76PjCH0+/f5ZiK5Lc7g==", got "dropbox".:
  dropbox-sdk (1.6.5) lib/dropbox_sdk.rb:627:in `finish'
  browse-everything (0.10.0) lib/browse_everything/driver/dropbox.rb:54:in `connect'
  browse-everything (0.10.0) app/controllers/browse_everything_controller.rb:19:in `auth'
```

**Comment by cam156** [comment]
I get the same error when I test dropbox in Sufia's spec internal app

**Comment by mbklein** [comment]
Dropbox tests are failing in the browse-everything suite as well.
