### ISSUE TITLE
Can't modify frozen assets path

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/browse-everything#94]
https://github.com/projecthydra-labs/browse-everything/blob/master/lib/browse_everything/engine.rb#L4

```
can't modify frozen Array
/home/travis/build/psu-stewardship/sufia/vendor/bundle/ruby/2.2.0/gems/browse-everything-0.8.1/lib/browse_everything/engine.rb:4:in `block in <class:Engine>'
/home/travis/build/psu-stewardship/sufia/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/travis/build/psu-stewardship/sufia/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
/home/travis/build/psu-stewardship/sufia/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/travis/build/psu-stewardship/sufia/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
/home/travis/build/psu-stewardship/sufia/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
/home/travis/build/psu-stewardship/sufia/spec/internal/config/environment.rb:5:in `<top (required)>'
/home/travis/build/psu-stewardship/sufia/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/home/travis/build/psu-stewardship/sufia/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/travis/build/psu-stewardship/sufia/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/travis/build/psu-stewardship/sufia/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/home/travis/build/psu-stewardship/sufia/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:328:in `require_environment!'
/home/travis/build/psu-stewardship/sufia/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/travis/build/psu-stewardship/sufia/vendor/bundle/ruby/2.2.0/bin/ruby_executable_hooks:15:in `eval'
/home/travis/build/psu-stewardship/sufia/vendor/bundle/ruby/2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jcoyne** [comment]
I don't think you need that wrapped in an `initializer` block.
